import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body>
        <div id="layout-wrapper" className="h-screen py-24">
          <Header />
          <div className="h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
